name: CI-CD Flask app to Apache Web server in AWS EC2

on:
  push:
    branches: 
      - main
      
jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
        
      #- name: 
